[build]
  functions = "netlify/functions"
  publish   = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from   = "/album"
  to     = "/album.html"
  status = 200

[[redirects]]
  from   = "/sucesso"
  to     = "/sucesso.html"
  status = 200
